import { Header } from "@/components/shared/header";
import { Footer } from "@/components/shared/footer";
import type { Metadata } from "next";
import './globals.css';
import { Hero } from "@/components/home/hero";
import { Searcher } from "@/components/home/varSearcher";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Header/>
        {children}
      </body>
    </html>
  );
}
